### ISSUE TITLE
About using Flat UI Pro

### ISSUE THREAD

**Issue by zaherg** [anomalylabs/streams-theme#3]
hey, 
I just noticed that you are publishing your less directory with `Flat UI Pro` which is not free nor under MIT license.

am not sure if you got a permission to publish this Paid version of `Flat UI Pro` for the public, I was thinking that you may use [Flat UI](https://github.com/designmodo/Flat-UI) the open source version which is much better if your code is under MIT.

**Comment by RyanThompson** [comment]
Hey there! Good catch, but I believe aside from the license of the addon (which Ill look into) that I am in the clear. I own a developer license for it (same for Redactor which is in the WYSIWYG field type).
